### ISSUE TITLE
Hera stacks: CGAL module

### ISSUE THREAD

**Issue by rhoneyager** [JCSDA-internal/jedi-stack#41]
This is in response to https://github.com/JCSDA-internal/soca/pull/468. 

The installation is header-only, but it depends on GMP and MPFR, which are not available on Hera. I am opening a ticket to get these installed.

@benjaminmenetrier, @mmiesch, @ytremolet is CGAL going to be a required component in the JEDI stack? If so, 1) I suggest that we add stack installation scripts for its dependencies, and 2) I need to update the requirements table for WCOSS before meeting with EMC next Friday.

**Comment by markjolah** [comment]
@rhoneyager  @mmiesch After looking into this I think we want to build with `CGAL_DISABLE_GMP` as described in: [Summary of CGAL's Configuration Variables](https://doc.cgal.org/latest/Manual/configurationvariables.html).  This will disable the need for both GMP and MPFR.  Both libraries are software-based extended-precision libraries, which are going to be way too slow to use in any important code.  We should be using just the native processor data types with CGal anyways.

I'm working on a PR today to update the CGal and fix the Intel compiler problems, and I'll enable this option too.

**Comment by mmiesch** [comment]
Great - thanks @markjolah for looking into that.  Would you do a PR to jedi-stack with this modification to build_cgal.sh?

**Comment by rhoneyager** [comment]
Hera sysadmins have installed the dependencies, and PRs are in jedi-stack. CGAL installed.
